FROM nginx:1.17.0-alpine

USER root

MAINTAINER Engin Polat (polatengin) <engin@enginpolat.com>

COPY ./dist /usr/share/nginx/html

RUN nginx

EXPOSE 80

LABEL maintainer="Engin Polat (polatengin) <engin@enginpolat.com>" \
      org.label-schema.docker.dockerfile="/Dockerfile" \
      org.label-schema.license="MIT" \
      org.label-schema.name="Keyboard Piano" \
      org.label-schema.vcs-type="Git" \
      org.label-schema.vcs-url="https://github.com/polatengin/paris"
